### PR TITLE
Fix windows directory handing during recursive uploads and downloads

### PR DESCRIPTION
**Pull request by dimara**
This patch set fixes kamaki in order to handle windows directories
that contain backslash as a separator properly.

Additionally it introduces a new command 'kamaki scripts verifyfs'
that verifies and fixes the directory structure of a container.

To reproduce an inconsistent state in Pithos do the following actions 
in a windows box with current stable kamaki:

  1) mkdir dir1/dir2/dir3
  2) echo adsfasdf > dir1/dir2/dir3/file
  3) kamaki file upload -r dir1

Then traverse this structure from Pithos UI.

### CODE REVIEW

**Comment by saxtouri** [comment]
It would be really helpful if you could separate the bugfix from the feature request, thanks.

**Comment by dimara** [comment]
There is no feature in this patch set. All of these patches are necessary to fix an existing case of corruption that can be triggered with a pretty common setup: kamaki on windows + pithos UI. This is a serious bugfix and should be included in a new hotfix release.

**Comment by dimara** [comment]
Any news on this?

Note that this is a serious bug that causes name corruption, structure inconsistencies, and should be fixed as soon as possible so that a new hotfix version gets released. It affects all Synnefo deployments, making them potentially unfunctional for end-users.

**Comment by saxtouri** [comment]
With the exception of 9c9f8d0e4649b53c70c6e7e06e7867a695282ccf , this path LGTM.

My objection to 9c9f8d0e4649b53c70c6e7e06e7867a695282ccf is that we should not attach a new functionality to an existing namespace in a hotfix, because:
* Hotfixes fix bugs, they should not enhance existing functionalities
* If the actual bug is fixed, new users won't have to apply the provided verification script
* The name of the command in this particular namespace ("container verify") might be confusing for some users.

On the other hand, we would like to keep the script because it might prove useful in many cases, and we also want to make it easy to use.

This is what we can do:
* Create a novel command namespace "scripts"
* Rename "kamaki container verify" to "kamaki scripts verifyfs"
* Adjust the code so that the container is supplied as a named argument "--container"
* Put the code in a separate location "kamaki/cli/contrib/scripts.py"

**Comment by dimara** [comment]
OK. So I expect you to write the base code of the new command namespace in a new hotfix-0.13.2 branch and then I will rebase this patch set and resubmit it. Thanks.

**Comment by dimara** [comment]
Any news on this? Shouldn't this be merged already?

**Comment by dimara** [comment]
Merged with PR 100.

**Pull request closed without merging**
